import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import onboardingRouter from "./onboarding.js";
import agentConfigRouter from "./agentConfig.js";
import connectRouter from "./connect.js";
import syncRouter from "./sync.js";
import testRouter from "./testRoutes.js";
import healthScanRouter from "./healthScan.js";
import normalizationRouter from "./normalization.js";
import fitmentRouter from "./fitment.js";
import probeRouter from "./probe.js";
import gatewayRouter from "./gateway.js";
import v1Router from "./v1/index.js";
import metricsRouter from "./metrics.js";
import feedsRouter from "./feeds.js";
import insightsRouter from "./insights.js";
import transactionsRouter from "./transactions.js";
import botDefenseRouter from "./botDefense.js";
import seederRouter from "./seeder.js";
import phaseRouter from "./phase.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/onboarding", phaseRouter);
router.use("/onboarding", onboardingRouter);
router.use("/onboarding", agentConfigRouter);
router.use("/onboarding", connectRouter);
router.use("/onboarding", syncRouter);
router.use("/onboarding", healthScanRouter);
router.use("/onboarding", normalizationRouter);
router.use("/onboarding", fitmentRouter);
router.use("/onboarding", probeRouter);
router.use("/onboarding", gatewayRouter);
router.use("/test", testRouter);
router.use("/test", seederRouter);
router.use("/v1", v1Router);
router.use(metricsRouter);
router.use(feedsRouter);
router.use(insightsRouter);
router.use(transactionsRouter);
router.use(botDefenseRouter);

export default router;
